# Generated by Django 2.1.7 on 2019-04-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webPeliculas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='director',
        ),
    ]
